# Avizo Project 950
# Avizo
# Generated by Avizo 9.5.0
remove -all
remove "grayScale.am" "physics.icol" "029_estaillades1_q01_fw085_ss_00001_0100.rec.16bit.tif" "tif_subvolume" "tif_filtered" "Extract Subvolume" "Non-Local Means Filter"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

#*****************User Input*******************
set Parent_dir Y:/live/069_estaillades1_q04_fw05_us/
#*****************User Input*******************

cd $Parent_dir
set files [glob -type d *]
set files_sort [lsort $files]

#length of file 
set f [llength $files_sort] 


for {set j 0} {$j<30} {incr j} {
set Parent_dir Y:/live/069_estaillades1_q04_fw05_us/
set file_name [lindex $files_sort $j]
set pwd [append Parent_dir $file_name]
set temp [glob -directory $pwd *.tif]
set name [lindex $temp 0]
set n [llength $temp]
cd $file_name
set hideNewModules 1

set hideNewModules 0
[load -tif +box 0 2016 0 2016 0 $n +mode 2 *tif] setLabel "tif.am"
"tif.am" setIconPosition 20 10
"tif.am" fire

set hideNewModules 0
create HxLatticeAccess "Extract Subvolume"
# check
"Extract Subvolume" setIconPosition 160 46
"Extract Subvolume" setVar "CustomHelp" {HxLatticeAccess}
"Extract Subvolume" data connect "tif.am"
"Extract Subvolume" time setMinMax 0 1
"Extract Subvolume" time setSubMinMax 0 1
"Extract Subvolume" time setValue 0
"Extract Subvolume" time setDiscrete 0
"Extract Subvolume" time setIncrement 0.01
"Extract Subvolume" time animationMode -once
"Extract Subvolume" time setAnimationDelay 10
"Extract Subvolume" fire
"Extract Subvolume" dataset setIndex 0 0
"Extract Subvolume" boxUnits setValue 0
"Extract Subvolume" boxMin setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxMin setValue 0 241
"Extract Subvolume" boxMin setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxMin setValue 1 223
"Extract Subvolume" boxMin setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxMin setValue 2 30
"Extract Subvolume" boxSize setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxSize setValue 0 1536
"Extract Subvolume" boxSize setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxSize setValue 1 1563
"Extract Subvolume" boxSize setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxSize setValue 2 1550
"Extract Subvolume" options setValue 0 0
"Extract Subvolume" options setToggleVisible 0 1
"Extract Subvolume" options setValue 1 0
"Extract Subvolume" options setToggleVisible 1 1
"Extract Subvolume" options setValue 2 1
"Extract Subvolume" options setToggleVisible 2 0
"Extract Subvolume" subsample setMinMax 0 -16777216 16777216
"Extract Subvolume" subsample setValue 0 4
"Extract Subvolume" subsample setMinMax 1 -16777216 16777216
"Extract Subvolume" subsample setValue 1 4
"Extract Subvolume" subsample setMinMax 2 -16777216 16777216
"Extract Subvolume" subsample setValue 2 4
"Extract Subvolume" timeSlider setMinMax 0 0
"Extract Subvolume" timeSlider setButtons 1
"Extract Subvolume" timeSlider setEditButton 1
"Extract Subvolume" timeSlider setIncrement 1
"Extract Subvolume" timeSlider setValue 0
"Extract Subvolume" timeSlider setSubMinMax 0 0
"Extract Subvolume" applyTransformToResult 1
"Extract Subvolume" fire
"Extract Subvolume" setViewerMask 16383
"Extract Subvolume" setPickable 1

set hideNewModules 0
[ "Extract Subvolume" create ] setLabel "tif_subvolume"
"tif_subvolume" setIconPosition 20 82
"tif_subvolume" master connect "Extract Subvolume" "result" 0
"tif_subvolume" sharedColormap disconnect
"tif_subvolume" sharedColormap setDefaultColor 0.8 0.8 0.8
"tif_subvolume" sharedColormap setDefaultAlpha 0.500000
"tif_subvolume" sharedColormap activateLocalRange 1
"tif_subvolume" sharedColormap setLocalMinMax 0.000000 1.000000
"tif_subvolume" sharedColormap enableAlpha 1
"tif_subvolume" sharedColormap enableAlphaToggle 1
"tif_subvolume" sharedColormap setAutoAdjustRangeMode 1
"tif_subvolume" sharedColormap setColorbarMinMax 0 65535
"tif_subvolume" fire
"tif_subvolume" fire
"tif_subvolume" setViewerMask 16383

set hideNewModules 0
create "Non-Local Means Filter" "Non-Local Means Filter"
"Non-Local Means Filter" setIconPosition 160 118
"Non-Local Means Filter" setVar "CustomHelp" {HxImageFilters_NonLocalMeans.html}
"Non-Local Means Filter" data connect "tif_subvolume"
"Non-Local Means Filter" setFilter nonLocalMeans
"Non-Local Means Filter" setFilterOrientation 2
"Non-Local Means Filter" fire
"Non-Local Means Filter" searchWindow setMinMax 0 1 2147483648
"Non-Local Means Filter" searchWindow setValue 0 21
"Non-Local Means Filter" neighborhood setMinMax 0 1 2147483648
"Non-Local Means Filter" neighborhood setValue 0 5
"Non-Local Means Filter" similarityValue setMinMax 0 9.99999974737875e-005 3.40282346638529e+038
"Non-Local Means Filter" similarityValue setValue 0 0.5
"Non-Local Means Filter" adaptive setValue 1
"Non-Local Means Filter" device setValue 0
"Non-Local Means Filter" cudaDevice setIndex 0 0
"Non-Local Means Filter" options setValue 0 1
"Non-Local Means Filter" options setToggleVisible 0 1
"Non-Local Means Filter" partitionSize setMinMax 0 9.99999997475243e-007 100
"Non-Local Means Filter" partitionSize setValue 0 0.296941578388214
"Non-Local Means Filter" setVar "CustomHelp" {HxImageFilters_NonLocalMeans.html}
"Non-Local Means Filter" applyTransformToResult 1
"Non-Local Means Filter" fire
"Non-Local Means Filter" setViewerMask 16383
"Non-Local Means Filter" setPickable 1

set hideNewModules 0
[ "Non-Local Means Filter" doIt hit; "Non-Local Means Filter"  fire;  "Non-Local Means Filter" getResult
 ] setLabel "tif_filtered"
"tif_filtered" setIconPosition 20 154
"tif_filtered" master connect "Non-Local Means Filter" "result" 0
"tif_filtered" sharedColormap disconnect
"tif_filtered" sharedColormap setDefaultColor 0.8 0.8 0.8
"tif_filtered" sharedColormap setDefaultAlpha 0.500000
"tif_filtered" sharedColormap activateLocalRange 1
"tif_filtered" sharedColormap setLocalMinMax 0.000000 1.000000
"tif_filtered" sharedColormap enableAlpha 1
"tif_filtered" sharedColormap enableAlphaToggle 1
"tif_filtered" sharedColormap setAutoAdjustRangeMode 1
"tif_filtered" sharedColormap setColorbarMinMax 0 65535
"tif_filtered" fire
"tif_filtered" fire
"tif_filtered" setViewerMask 16383

set hideNewModules 0

set name_trim [string trimright $name "00001_0001.rec.16bit.tif"]

set output [append name_trim _filtered.am]

tif_filtered save "AmiraMesh" $output
cd ..
unset pwd
echo $j
echo $f
remove -all


}