# Avizo Project 950
# Avizo
# Generated by Avizo 9.5.0
remove -all
remove "labels.am" "031_estaillades1_q01_fw085_ss_0003_seg.tif" "031_estaillades1_q01_fw085_ss_seg.colormap" "031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" "031_estaillades1_q01_fw085_ss_seg.label" "031_estaillades1_q01_fw085_ss_seg.Label-Analysis" "Convert Image Type" "Label Analysis"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show


#*****************User Input*******************
set Parent_dir Y:/live/069_estaillades1_q04_fw05_us/
#*****************User Input*******************

cd $Parent_dir
set files [glob -type d *]
set files_sort [lsort $files]

#length of file 
set n [llength $files_sort] 


for {set i 26} {$i<30} {incr i} {
set Parent_dir Y:/live/069_estaillades1_q04_fw05_us/
set file_name [lindex $files_sort $i]
set pwd [append Parent_dir $file_name]
set temp [glob -directory $pwd *seg.tif]
cd $pwd 
set name [lindex $temp 0]
echo $i
#time in s
set t    [expr "$i+1"]
echo $t


set hideNewModules 0
[ load Y:/live/data_processing/pore_space_segmented_poreMBs.to-labelfield-32_bits.am ] setLabel "pore_space_segmented_poreMBs_subvolume.am"


set hideNewModules 0
create HxArithmetic "Arithmetic"
"Arithmetic" setIconPosition 376 257
"Arithmetic" setVar "CustomHelp" {HxArithmetic}
"Arithmetic" inputA connect "pore_space_segmented_poreMBs_subvolume.am"
"Arithmetic" fire
"Arithmetic" resultChannels setIndex 0 0
"Arithmetic" nValues setMinMax 0 -16777216 16777216
"Arithmetic" nValues setValue 0 1
"Arithmetic" expr0 setState {(a> 0) *a}
"Arithmetic" resultType setValue 0
"Arithmetic" resultLocation setValue 0
"Arithmetic" resolution setMinMax 0 1 100000
"Arithmetic" resolution setValue 0 64
"Arithmetic" resolution setMinMax 1 1 100000
"Arithmetic" resolution setValue 1 64
"Arithmetic" resolution setMinMax 2 1 100000
"Arithmetic" resolution setValue 2 64
"Arithmetic" minBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 0 -1
"Arithmetic" minBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 1 -1
"Arithmetic" minBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 2 -1
"Arithmetic" maxBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 0 1
"Arithmetic" maxBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 1 1
"Arithmetic" maxBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 2 1
"Arithmetic" options setValue 0 0
"Arithmetic" options setToggleVisible 0 1
"Arithmetic" applyTransformToResult 1
"Arithmetic" fire
"Arithmetic" setViewerMask 65535
"Arithmetic" setPickable 1

set hideNewModules 0
[ {Arithmetic} create result ] setLabel "Result2"
"Result2" setIconPosition 381 373
"Result2" master connect "Arithmetic" "result" 0
"Result2" fire
"Result2" fire
"Result2" setViewerMask 65535

set hideNewModules 0
if { ![info exists TMPIO48] } { set TMPIO48 [load -tif +mode 100 +box 241.12 1776.89 223.111 1785.89 30.0188 1579.99 $name] }
[ lindex $TMPIO48 0 ] setLabel "031_estaillades1_q01_fw085_ss_0003_seg.tif"
"031_estaillades1_q01_fw085_ss_0003_seg.tif" setIconPosition 20 10
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap disconnect
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap setDefaultColor 0.8 0.8 0.8
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap setDefaultAlpha 0.500000
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap activateLocalRange 1
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap setLocalMinMax 0.000000 1.000000
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap enableAlpha 1
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap enableAlphaToggle 1
"031_estaillades1_q01_fw085_ss_0003_seg.tif" sharedColormap setAutoAdjustRangeMode 1
"031_estaillades1_q01_fw085_ss_0003_seg.tif" fire
"031_estaillades1_q01_fw085_ss_0003_seg.tif" fire
"031_estaillades1_q01_fw085_ss_0003_seg.tif" setViewerMask 16383


set hideNewModules 0
create HxCastField "Convert Image Type"
"Convert Image Type" setIconPosition 83 96
"Convert Image Type" setVar "CustomHelp" {HxCastField}
"Convert Image Type" data connect "031_estaillades1_q01_fw085_ss_0003_seg.tif"
"Convert Image Type" colormap disconnect
"Convert Image Type" colormap setDefaultColor 1 0.8 0.5
"Convert Image Type" colormap setDefaultAlpha 0.500000
"Convert Image Type" colormap activateLocalRange 1
"Convert Image Type" colormap setLocalMinMax 0.000000 1.000000
"Convert Image Type" colormap enableAlpha 1
"Convert Image Type" colormap enableAlphaToggle 1
"Convert Image Type" colormap setAutoAdjustRangeMode 1
"Convert Image Type" colormap setColorbarMinMax 0 120
"Convert Image Type" fire
"Convert Image Type" outputType setIndex 0 6
"Convert Image Type" scaling setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Convert Image Type" scaling setValue 0 1
"Convert Image Type" scaling setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Convert Image Type" scaling setValue 1 0
"Convert Image Type" voxelGridOptions setValue 0 0
"Convert Image Type" voxelGridOptions setToggleVisible 0 1
"Convert Image Type" colorFieldOptions setIndex 0 0
"Convert Image Type" applyTransformToResult 1
"Convert Image Type" fire
"Convert Image Type" setViewerMask 16383
"Convert Image Type" setPickable 1

set hideNewModules 0
[ {Convert Image Type} create result ] setLabel "031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits"
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" setIconPosition 29 138
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" master connect "Convert Image Type" "result" 0
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap connect "labels.am"
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap setDefaultColor 0.8 0.8 0.8
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap setDefaultAlpha 0.500000
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap activateLocalRange 1
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap setLocalMinMax 1.000000 8.000000
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap enableAlpha 1
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap enableAlphaToggle 1
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap setAutoAdjustRangeMode 1
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" sharedColormap setColorbarMinMax 1 8
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" fire
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" primary setIndex 0 0
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" fire
"031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" setViewerMask 16383



set hideNewModules 0
create HxAnalyzeLabels "Label Analysis"
"Label Analysis" setIconPosition 79 202
"Label Analysis" setVar "CustomHelp" {HxAnalyzeLabels}
"Label Analysis" data connect "031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits"
"Label Analysis" fire
"Label Analysis" interpretation setValue 0
"Label Analysis" sequenceMode setValue 0
labelMeasure setAttributes feret2d 0 18 36 54 72 90 108 126 144 162
labelMeasure setAttributes feret3d 31
labelMeasure setAttributes cooccurrence 0 0
labelMeasure setAttributes histogram 1 0 255 1
labelMeasure setAttributes quantile 0.1 0.1 0.1 0.1 0.1 0.1
labelMeasure setAttributes breadth3d 10
"Label Analysis" measures setState {"ganglia_analysis" Area3d Volume3d EqDiameter Mean IntegralTotalCurvature BaryCenterX BaryCenterY BaryCenterZ Width3d Length3d Maximum Minimum BoundingBoxDz FirstPointZ}
"Label Analysis" showAnalysis setValue 0 1
"Label Analysis" showAnalysis setToggleVisible 0 1
"Label Analysis" applyTransformToResult 1
"Label Analysis" fire
"Label Analysis" setViewerMask 16383
"Label Analysis" setPickable 1

set hideNewModules 0
[ {Label Analysis} create AnlOut ] setLabel "031_estaillades1_q01_fw085_ss_seg.Label-Analysis"
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis" setIconPosition -29 274
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis" master connect "Label Analysis" "AnlOut" 0
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis" fire
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis" fire
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis" setViewerMask 16383

set hideNewModules 0
[ {Label Analysis} create ImgOutLab ] setLabel "031_estaillades1_q01_fw085_ss_seg.label"
"031_estaillades1_q01_fw085_ss_seg.label" setIconPosition -29 238
"031_estaillades1_q01_fw085_ss_seg.label" master connect "Label Analysis" "ImgOutLab" 1
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap connect "labels.am"
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap setDefaultColor 0.8 0.8 0.8
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap setDefaultAlpha 0.500000
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap activateLocalRange 1
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap setLocalMinMax 1.000000 8.000000
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap enableAlpha 1
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap enableAlphaToggle 1
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap setAutoAdjustRangeMode 1
"031_estaillades1_q01_fw085_ss_seg.label" sharedColormap setColorbarMinMax 1 8
"031_estaillades1_q01_fw085_ss_seg.label" fire
"031_estaillades1_q01_fw085_ss_seg.label" primary setIndex 0 0
"031_estaillades1_q01_fw085_ss_seg.label" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"031_estaillades1_q01_fw085_ss_seg.label" fire
"031_estaillades1_q01_fw085_ss_seg.label" setViewerMask 16383
"031_estaillades1_q01_fw085_ss_seg.label" select



set hideNewModules 0
create HxCastField "Convert Image Type 3"
"Convert Image Type 3" setIconPosition 202 152
"Convert Image Type 3" setVar "CustomHelp" {HxCastField}
"Convert Image Type 3" data connect "031_estaillades1_q01_fw085_ss_seg.label"
"Convert Image Type 3" colormap disconnect
"Convert Image Type 3" colormap setDefaultColor 1 0.8 0.5
"Convert Image Type 3" colormap setDefaultAlpha 0.500000
"Convert Image Type 3" colormap activateLocalRange 1
"Convert Image Type 3" colormap setLocalMinMax 0.000000 22.000000
"Convert Image Type 3" colormap enableAlpha 1
"Convert Image Type 3" colormap enableAlphaToggle 1
"Convert Image Type 3" colormap setAutoAdjustRangeMode 1
"Convert Image Type 3" colormap setColorbarMinMax 0 120
"Convert Image Type 3" fire
"Convert Image Type 3" outputType setIndex 0 0
"Convert Image Type 3" scaling setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Convert Image Type 3" scaling setValue 0 1
"Convert Image Type 3" scaling setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Convert Image Type 3" scaling setValue 1 0
"Convert Image Type 3" voxelGridOptions setValue 0 0
"Convert Image Type 3" voxelGridOptions setToggleVisible 0 1
"Convert Image Type 3" colorFieldOptions setIndex 0 0
"Convert Image Type 3" applyTransformToResult 1
"Convert Image Type 3" fire
"Convert Image Type 3" setViewerMask 16383
"Convert Image Type 3" setPickable 1


set hideNewModules 0
[ {Convert Image Type 3} create result ] setLabel "031_estaillades1_q01_fw085_ss_seg.to-byte"
"031_estaillades1_q01_fw085_ss_seg.to-byte" setIconPosition 391 143
"031_estaillades1_q01_fw085_ss_seg.to-byte" master connect "Convert Image Type 3" "result" 0
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap disconnect
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap setDefaultColor 0.8 0.8 0.8
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap setDefaultAlpha 0.500000
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap activateLocalRange 1
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap setLocalMinMax 0.000000 1.000000
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap enableAlpha 1
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap enableAlphaToggle 1
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap setAutoAdjustRangeMode 1
"031_estaillades1_q01_fw085_ss_seg.to-byte" sharedColormap setColorbarMinMax 0 22
"031_estaillades1_q01_fw085_ss_seg.to-byte" fire
"031_estaillades1_q01_fw085_ss_seg.to-byte" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"031_estaillades1_q01_fw085_ss_seg.to-byte" fire
"031_estaillades1_q01_fw085_ss_seg.to-byte" setViewerMask 16383

set hideNewModules 0
create HxAnalyzeLabels "Label Analysis 2"
"Label Analysis 2" setIconPosition 421 76
"Label Analysis 2" setVar "CustomHelp" {HxAnalyzeLabels}
"Label Analysis 2" data connect "Result2"
"Label Analysis 2" intensityImage connect "031_estaillades1_q01_fw085_ss_seg.to-byte"
"Label Analysis 2" fire
"Label Analysis 2" interpretation setValue 0
"Label Analysis 2" sequenceMode setValue 0
labelMeasure setAttributes feret2d 0 18 36 54 72 90 108 126 144 162
labelMeasure setAttributes feret3d 31
labelMeasure setAttributes cooccurrence 0 0
labelMeasure setAttributes histogram 1 0 255 1
labelMeasure setAttributes quantile 0.1 0.1 0.1 0.1 0.1 0.1
labelMeasure setAttributes breadth3d 10
"Label Analysis 2" measures setState {"ganglia_analysis" Area3d Volume3d EqDiameter Mean BaryCenterX BaryCenterY BaryCenterZ Width3d Length3d Maximum Minimum BoundingBoxDz FirstPointZ}
"Label Analysis 2" showAnalysis setValue 0 1
"Label Analysis 2" showAnalysis setToggleVisible 0 1
"Label Analysis 2" applyTransformToResult 1
"Label Analysis 2" fire
"Label Analysis 2" setViewerMask 16383
"Label Analysis 2" setPickable 1


set hideNewModules 0
[ {Label Analysis 2} create AnlOut ] setLabel "031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2"
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2" setIconPosition -29 274
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2" master connect "Label Analysis 2" "AnlOut" 0
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2" fire
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2" fire
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2" setViewerMask 16383


set output1  "_seg_noMB.measure.csv"
set output2  "_seg_MB.measure.csv"
set output3  "_labels.am"

set combined1 $file_name$output1
set combined2 $file_name$output2
set combined3 $file_name$output3


"031_estaillades1_q01_fw085_ss_seg.Label-Analysis" exportData "CSV tabulator separated" $combined1
"031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2" exportData "CSV tabulator separated" $combined2
"031_estaillades1_q01_fw085_ss_seg.label" save "AmiraMesh" $combined3
#remove "031_estaillades1_q01_fw085_ss_seg.Label-Analysis-2" "Label Analysis 2" "031_estaillades1_q01_fw085_ss_seg.to-byte" "Convert Image Type" "031_estaillades1_q01_fw085_ss_0003_seg.tif" "Convert Image Type 3" "031_estaillades1_q01_fw085_ss_seg.label" "031_estaillades1_q01_fw085_ss_seg.Label-Analysis" "031_estaillades1_q01_fw085_ss_seg.to-labelfield-8_bits" "Label Analysis"
remove -all 
cd .. 
unset TMPIO48

}