# Avizo Project 950
# Avizo
# Generated by Avizo 9.5.0
remove -all
remove "grayScale.am" "physics.icol" "029_estaillades1_q01_fw085_ss_filtered.am" "004_estaillades1_DI_0001-filtered.am" "029_estaillades1_q01_fw085_ss_filtered.Resampled.am" "Register Images" "Resample Transformed Image"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show



#*****************User Input*******************
set Parent_dir Y:/live/058_estaillades1_q04_fw085_ss/
#*****************User Input*******************

cd $Parent_dir
set files [glob -type d *]
set files_sort [lsort $files]

#length of file 
set f [llength $files_sort] 

#load reference image outside loop to save time 
set hideNewModules 0
[ load Y:/live/data_processing/004_estaillades1_DI_0001_filtered.am ] setLabel "004_estaillades1_DI_0001-filtered.am"
"004_estaillades1_DI_0001-filtered.am" setIconPosition 69 46
"004_estaillades1_DI_0001-filtered.am" fire
"004_estaillades1_DI_0001-filtered.am" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"004_estaillades1_DI_0001-filtered.am" fire
"004_estaillades1_DI_0001-filtered.am" setViewerMask 16383

for {set j 0} {$j<$f} {incr j} {
set Parent_dir Y:/live/058_estaillades1_q04_fw085_ss/
set file_name [lindex $files_sort $j]
set pwd [append Parent_dir $file_name]
set temp [glob -directory $pwd *.tif]
set name [lindex $temp 0]
set n [llength $temp]
cd $file_name
set hideNewModules 1


set hideNewModules 0
[ load *filtered.am ] setLabel "029_estaillades1_q01_fw085_ss_filtered.am"
"029_estaillades1_q01_fw085_ss_filtered.am" setIconPosition 43 163
"029_estaillades1_q01_fw085_ss_filtered.am" fire
"029_estaillades1_q01_fw085_ss_filtered.am" setTransform 0.999997 -0.000115814 0.00260979 0 0.000120293 0.999998 -0.00171582 0 -0.00260964 0.00171612 0.999995 0 10.8134 -7.14081 -0.655457 1
"029_estaillades1_q01_fw085_ss_filtered.am" fire
"029_estaillades1_q01_fw085_ss_filtered.am" setViewerMask 16382


set hideNewModules 0
create HxAffineRegistration "Register Images"
"Register Images" setIconPosition 324 88
"Register Images" setVar "CustomHelp" {HxAffineRegistration}
"Register Images" model connect "029_estaillades1_q01_fw085_ss_filtered.am"
"Register Images" reference connect "004_estaillades1_DI_0001-filtered.am"
"Register Images" fire
"Register Images" optimizer setIndex 0 0
"Register Images" optimizer setIndex 1 0
"Register Images" extensiveSearch setValue 0 0
"Register Images" extensiveSearch setToggleVisible 0 1
"Register Images" step setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" step setValue 0 312.756286621094
"Register Images" step setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" step setValue 1 0.166749998927116
"Register Images" nLevelsGradient setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" nLevelsGradient setValue 0 1
"Register Images" nLevelsGradient setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" nLevelsGradient setValue 1 9.99999974737875e-005
"Register Images" coarsestResolution setMinMax 0 1 768
"Register Images" coarsestResolution setValue 0 51
"Register Images" coarsestResolution setMinMax 1 1 781
"Register Images" coarsestResolution setValue 1 52
"Register Images" coarsestResolution setMinMax 2 1 775
"Register Images" coarsestResolution setValue 2 51
"Register Images" metric setIndex 0 0
"Register Images" histogramRangeRef setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" histogramRangeRef setValue 0 0
"Register Images" histogramRangeRef setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" histogramRangeRef setValue 1 65535
"Register Images" histogramRangeMod setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" histogramRangeMod setValue 0 0
"Register Images" histogramRangeMod setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Register Images" histogramRangeMod setValue 1 65535
"Register Images" histogramBins setMinMax 0 -16777216 16777216
"Register Images" histogramBins setValue 0 255
"Register Images" histogramBins setMinMax 1 -16777216 16777216
"Register Images" histogramBins setValue 1 255
"Register Images" thresholdModelOutsideReference setMinMax 0 1
"Register Images" thresholdModelOutsideReference setButtons 0
"Register Images" thresholdModelOutsideReference setEditButton 1
"Register Images" thresholdModelOutsideReference setIncrement 0.1
"Register Images" thresholdModelOutsideReference setValue 0.2
"Register Images" thresholdModelOutsideReference setSubMinMax 0 1
"Register Images" options setValue 0 1
"Register Images" options setToggleVisible 0 1
"Register Images" localizers setValue 0 0
"Register Images" localizers setToggleVisible 0 1
"Register Images" transform setValue 0 1
"Register Images" transform setToggleVisible 0 1
"Register Images" transform setValue 1 0
"Register Images" transform setToggleVisible 1 1
"Register Images" transform setValue 2 0
"Register Images" transform setToggleVisible 2 1
"Register Images" transform setValue 3 0
"Register Images" transform setToggleVisible 3 1
"Register Images" disableRotation setValue 0 0
"Register Images" disableRotation setToggleVisible 0 1
"Register Images" register setValue 1
"Register Images" applyTransformToResult 1
"Register Images" fire
"Register Images" setViewerMask 16383
"Register Images" setPickable 1
"Register Images" fire


#transform image to reg thresheld images
set scale [029_estaillades1_q01_fw085_ss_filtered.am getScaleFactor]
set trans [029_estaillades1_q01_fw085_ss_filtered.am getTranslation]
set rot [029_estaillades1_q01_fw085_ss_filtered.am getRotation]

set scale_1 [lindex $scale 0]
set scale_2 [lindex $scale 1]
set scale_3 [lindex $scale 2]

set trans_1 [lindex $trans 0]
set trans_2 [lindex $trans 1]
set trans_3 [lindex $trans 2]

set rot_1 [lindex $rot 0]
set rot_2 [lindex $rot 1]
set rot_3 [lindex $rot 2]
set rot_4 [lindex $rot 3]

029_estaillades1_q01_fw085_ss_filtered.am setScaleFactor $scale_1 $scale_2 $scale_3
029_estaillades1_q01_fw085_ss_filtered.am setTranslation $trans_1 $trans_2 $trans_3
029_estaillades1_q01_fw085_ss_filtered.am setRotation $rot_1 $rot_2 $rot_3 $rot_4

set hideNewModules 0
create HxApplyTransform "Resample Transformed Image"
"Resample Transformed Image" setIconPosition 40 229
"Resample Transformed Image" setVar "CustomHelp" {HxApplyTransform}
"Resample Transformed Image" data connect "029_estaillades1_q01_fw085_ss_filtered.am"
"Resample Transformed Image" reference connect "004_estaillades1_DI_0001-filtered.am"
"Resample Transformed Image" fire
"Resample Transformed Image" interpolation setIndex 0 1
"Resample Transformed Image" mode setValue 0
"Resample Transformed Image" preserve setValue 0
"Resample Transformed Image" paddingValue setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Resample Transformed Image" paddingValue setValue 0 0
"Resample Transformed Image" applyTransformToResult 0
"Resample Transformed Image" fire
"Resample Transformed Image" setViewerMask 16383
"Resample Transformed Image" setPickable 1

set hideNewModules 0
[ "Resample Transformed Image" create] setLabel "029_estaillades1_q01_fw085_ss.Resampled"
"029_estaillades1_q01_fw085_ss.Resampled" setIconPosition 177 203
"029_estaillades1_q01_fw085_ss.Resampled" master connect "Resample Transformed Image"
"029_estaillades1_q01_fw085_ss.Resampled" fire



set name_trim [string trimright $name "00001_0001.rec.16bit.tif"]
set output [append name_trim _Resampled.am]
029_estaillades1_q01_fw085_ss.Resampled save "AmiraMesh" $output
unset pwd
remove -all
#remove "Resample Transformed Image" "029_estaillades1_q01_fw085_ss.Resampled" "029_estaillades1_q01_fw085_ss_filtered.am" "Register Images"
cd ..
}
