# Avizo Project 950
# Avizo
# Generated by Avizo 9.5.0
remove -all
remove "temperature.icol" "labels.am" "029_estaillades1_q01_fw085_ss_Resampled.am" "008_estaillades1_KI_4_0001.rec.Resampled.am" "Result2" "Result2.thresholded" "pore_space_segmented.am" "Result2.masked" "Result2.filtered" "029_estaillades1_q01_fw085_ss_00001_seg.am" "Arithmetic" "Interactive Thresholding" "Mask" "Remove Small Spots" "Remove Small Holes"

# Create viewers
viewer setVertical 1

viewer 1 setTransparencyType 6
viewer 1 setAutoRedraw 0
viewer 1 show
mainWindow show


set hideNewModules 0
[ load Y:/live/008_estaillades1_KI_4/008_estaillades1_KI_4_0001.rec.Resampled.am ] setLabel "008_estaillades1_KI_4_0001.rec.Resampled.am"
"008_estaillades1_KI_4_0001.rec.Resampled.am" setIconPosition 17 191
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap disconnect
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap setDefaultAlpha 0.500000
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap activateLocalRange 1
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap setLocalMinMax 0.000000 1.000000
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap enableAlpha 1
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap enableAlphaToggle 1
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap setAutoAdjustRangeMode 1
"008_estaillades1_KI_4_0001.rec.Resampled.am" sharedColormap setColorbarMinMax 0 63402
"008_estaillades1_KI_4_0001.rec.Resampled.am" fire
"008_estaillades1_KI_4_0001.rec.Resampled.am" fire
"008_estaillades1_KI_4_0001.rec.Resampled.am" setViewerMask 65535
"008_estaillades1_KI_4_0001.rec.Resampled.am" select

set hideNewModules 0
[ load Y:/live/data_processing/pore_space_segmented.am ] setLabel "pore_space_segmented.am"
"pore_space_segmented.am" setIconPosition 118 550
"pore_space_segmented.am" sharedColormap connect "labels.am"
"pore_space_segmented.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"pore_space_segmented.am" sharedColormap setDefaultAlpha 0.500000
"pore_space_segmented.am" sharedColormap activateLocalRange 1
"pore_space_segmented.am" sharedColormap setLocalMinMax 1.000000 8.000000
"pore_space_segmented.am" sharedColormap enableAlpha 1
"pore_space_segmented.am" sharedColormap enableAlphaToggle 1
"pore_space_segmented.am" sharedColormap setAutoAdjustRangeMode 1
"pore_space_segmented.am" sharedColormap setColorbarMinMax 1 8
"pore_space_segmented.am" fire
"pore_space_segmented.am" primary setIndex 0 0
"pore_space_segmented.am" fire
"pore_space_segmented.am" setViewerMask 65535


#*****************User Input*******************
set Parent_dir Y:/live/044_estaillades1_q01_fw05_ss/
#*****************User Input*******************

cd $Parent_dir
set files [glob -type d *]
set files_sort [lsort $files]

#length of file 
set f [llength $files_sort] 

for {set j 10} {$j<20} {incr j} {
set Parent_dir Y:/live/044_estaillades1_q01_fw05_ss/
set file_name [lindex $files_sort $j]
set pwd [append Parent_dir $file_name]
set temp [glob -directory $pwd *.tif]
set name [lindex $temp 0]
set n [llength $temp]
cd $file_name
set hideNewModules 1

set hideNewModules 0
[ load *Resampled.am ] setLabel "029_estaillades1_q01_fw085_ss_Resampled.am"
"029_estaillades1_q01_fw085_ss_Resampled.am" setIconPosition 30 255
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap disconnect
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap setDefaultAlpha 0.500000
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap activateLocalRange 1
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap setLocalMinMax 0.000000 1.000000
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap enableAlpha 1
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap enableAlphaToggle 1
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap setAutoAdjustRangeMode 1
"029_estaillades1_q01_fw085_ss_Resampled.am" sharedColormap setColorbarMinMax 0 64899
"029_estaillades1_q01_fw085_ss_Resampled.am" fire
"029_estaillades1_q01_fw085_ss_Resampled.am" fire
"029_estaillades1_q01_fw085_ss_Resampled.am" setViewerMask 65535



set hideNewModules 0
create HxArithmetic "Arithmetic"
"Arithmetic" setIconPosition 376 257
"Arithmetic" setVar "CustomHelp" {HxArithmetic}
"Arithmetic" inputA connect "008_estaillades1_KI_4_0001.rec.Resampled.am"
"Arithmetic" inputB connect "029_estaillades1_q01_fw085_ss_Resampled.am"
"Arithmetic" fire
"Arithmetic" resultChannels setIndex 0 0
"Arithmetic" nValues setMinMax 0 -16777216 16777216
"Arithmetic" nValues setValue 0 1
"Arithmetic" expr0 setState {a-b }
"Arithmetic" resultType setValue 0
"Arithmetic" resultLocation setValue 0
"Arithmetic" resolution setMinMax 0 1 100000
"Arithmetic" resolution setValue 0 64
"Arithmetic" resolution setMinMax 1 1 100000
"Arithmetic" resolution setValue 1 64
"Arithmetic" resolution setMinMax 2 1 100000
"Arithmetic" resolution setValue 2 64
"Arithmetic" minBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 0 -1
"Arithmetic" minBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 1 -1
"Arithmetic" minBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 2 -1
"Arithmetic" maxBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 0 1
"Arithmetic" maxBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 1 1
"Arithmetic" maxBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 2 1
"Arithmetic" options setValue 0 0
"Arithmetic" options setToggleVisible 0 1
"Arithmetic" applyTransformToResult 1
"Arithmetic" fire
"Arithmetic" setViewerMask 65535
"Arithmetic" setPickable 1

set hideNewModules 0
[ {Arithmetic} create result ] setLabel "Result2"
"Result2" setIconPosition 381 373
"Result2" master connect "Arithmetic" "result" 0
"Result2" sharedColormap disconnect
"Result2" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result2" sharedColormap setDefaultAlpha 0.500000
"Result2" sharedColormap activateLocalRange 1
"Result2" sharedColormap setLocalMinMax 0.000000 1.000000
"Result2" sharedColormap enableAlpha 1
"Result2" sharedColormap enableAlphaToggle 1
"Result2" sharedColormap setAutoAdjustRangeMode 1
"Result2" sharedColormap setColorbarMinMax 0 46417
"Result2" fire
"Result2" fire
"Result2" setViewerMask 65535

#Interactive thresholding 
set hideNewModules 0
create HxInteractiveThreshold "Interactive Thresholding"
"Interactive Thresholding" setViewerMask 0
"Interactive Thresholding" setIconPosition 328 426
"Interactive Thresholding" setVar "CustomHelp" {HxInteractiveThreshold}
set hideNewModules 0

"Interactive Thresholding" data connect "Result2"
"Interactive Thresholding" inputColorMap setDefaultColor 1 0.8 0.5
"Interactive Thresholding" inputColorMap setDefaultAlpha 0.500000
"Interactive Thresholding" inputColorMap activateLocalRange 1
"Interactive Thresholding" inputColorMap setLocalMinMax 0.000000 46417.000000
"Interactive Thresholding" inputColorMap enableAlpha 1
"Interactive Thresholding" inputColorMap enableAlphaToggle 1
"Interactive Thresholding" inputColorMap setAutoAdjustRangeMode 1
"Interactive Thresholding" inputColorMap setColorbarMinMax 0 46417
"Interactive Thresholding" fire
"Interactive Thresholding" preview setValue 0 1
"Interactive Thresholding" preview setToggleVisible 0 1
"Interactive Thresholding" preview setValue 1 0
"Interactive Thresholding" preview setToggleVisible 1 1
"Interactive Thresholding" orientation setValue 0
"Interactive Thresholding" sliceNumber setMinMax 0 1549
"Interactive Thresholding" sliceNumber setButtons 1
"Interactive Thresholding" sliceNumber setEditButton 1
"Interactive Thresholding" sliceNumber setIncrement 1
"Interactive Thresholding" sliceNumber setValue 1264
"Interactive Thresholding" sliceNumber setSubMinMax 0 1549
"Interactive Thresholding" rendering setValue 0
"Interactive Thresholding" intensityRange setMinMax 0 65535
"Interactive Thresholding" intensityRange setValues 2000 7775
"Interactive Thresholding" intensityRange setButtons 0
"Interactive Thresholding" intensityRange setEditButton 1
"Interactive Thresholding" intensityRange setIncrement 4369
"Interactive Thresholding" intensityRange setSubMinMax 0 0
"Interactive Thresholding" colorMask setColor 0 0 0 1
"Interactive Thresholding" applyTransformToResult 1
"Interactive Thresholding" fire
"Interactive Thresholding" setViewerMask 0
"Interactive Thresholding" setPickable 1

set hideNewModules 0
[ "Interactive Thresholding" doIt hit; "Interactive Thresholding" fire; "Interactive Thresholding" getResult
 ] setLabel "Result2.thresholded"
"Result2.thresholded" setIconPosition 340 495
"Result2.thresholded" master connect "Interactive Thresholding" "result" 0
"Result2.thresholded" sharedColormap connect "labels.am"
"Result2.thresholded" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result2.thresholded" sharedColormap setDefaultAlpha 0.500000
"Result2.thresholded" sharedColormap activateLocalRange 1
"Result2.thresholded" sharedColormap setLocalMinMax 1.000000 8.000000
"Result2.thresholded" sharedColormap enableAlpha 1
"Result2.thresholded" sharedColormap enableAlphaToggle 1
"Result2.thresholded" sharedColormap setAutoAdjustRangeMode 1
"Result2.thresholded" sharedColormap setColorbarMinMax 1 8
"Result2.thresholded" fire
"Result2.thresholded" primary setIndex 0 0
"Result2.thresholded" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"Result2.thresholded" fire
"Result2.thresholded" setViewerMask 65535

set hideNewModules 0
create mask "Mask"
"Mask" setIconPosition 406 558
"Mask" setVar "CustomHelp" {mask.html}
"Mask" interpretation setValue 0
"Mask" outputLocation setIndex 0 0
"Mask" inputImage connect "Result2.thresholded"
"Mask" inputBinaryImage connect "pore_space_segmented.am"
"Mask" applyTransformToResult 1
"Mask" fire
"Mask" setViewerMask 65535
"Mask" setPickable 1

set hideNewModules 0
[ {Mask} create ImgOut ] setLabel "Result2.masked"
"Result2.masked" setIconPosition 374 624
"Result2.masked" master connect "Mask" "ImgOut" 0
"Result2.masked" sharedColormap connect "labels.am"
"Result2.masked" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result2.masked" sharedColormap setDefaultAlpha 0.500000
"Result2.masked" sharedColormap activateLocalRange 1
"Result2.masked" sharedColormap setLocalMinMax 1.000000 8.000000
"Result2.masked" sharedColormap enableAlpha 1
"Result2.masked" sharedColormap enableAlphaToggle 1
"Result2.masked" sharedColormap setAutoAdjustRangeMode 1
"Result2.masked" sharedColormap setColorbarMinMax 1 8
"Result2.masked" fire
"Result2.masked" primary setIndex 0 0
"Result2.masked" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"Result2.masked" fire
"Result2.masked" setViewerMask 65535

set hideNewModules 0
create removalsmallspots "Remove Small Spots"
"Remove Small Spots" setIconPosition 374 677
"Remove Small Spots" setVar "CustomHelp" {removalsmallspots.html}
"Remove Small Spots" interpretation setValue 0
"Remove Small Spots" outputLocation setIndex 0 0
"Remove Small Spots" inputImage connect "Result2.masked"
"Remove Small Spots" size setMinMax 0 0 3.40282346638529e+038
"Remove Small Spots" size setValue 0 5000
"Remove Small Spots" applyTransformToResult 1
"Remove Small Spots" fire
"Remove Small Spots" setViewerMask 65535
"Remove Small Spots" setPickable 1

set hideNewModules 0
[ {Remove Small Spots} create ImgOut ] setLabel "Result2.filtered"
"Result2.filtered" setIconPosition 394 722
"Result2.filtered" master connect "Remove Small Spots" "ImgOut" 0
"Result2.filtered" sharedColormap connect "labels.am"
"Result2.filtered" sharedColormap setDefaultColor 0.8 0.8 0.8
"Result2.filtered" sharedColormap setDefaultAlpha 0.500000
"Result2.filtered" sharedColormap activateLocalRange 1
"Result2.filtered" sharedColormap setLocalMinMax 1.000000 8.000000
"Result2.filtered" sharedColormap enableAlpha 1
"Result2.filtered" sharedColormap enableAlphaToggle 1
"Result2.filtered" sharedColormap setAutoAdjustRangeMode 1
"Result2.filtered" sharedColormap setColorbarMinMax 1 8
"Result2.filtered" fire
"Result2.filtered" primary setIndex 0 0
"Result2.filtered" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"Result2.filtered" fire
"Result2.filtered" setViewerMask 65535

set hideNewModules 0
create removalsmallholes "Remove Small Holes"
"Remove Small Holes" setIconPosition 396 769
"Remove Small Holes" setVar "CustomHelp" {removalsmallholes.html}
"Remove Small Holes" interpretation setValue 0
"Remove Small Holes" outputLocation setIndex 0 0
"Remove Small Holes" inputBinaryImage connect "Result2.filtered"
"Remove Small Holes" size setMinMax 0 0 3.40282346638529e+038
"Remove Small Holes" size setValue 0 1000
"Remove Small Holes" applyTransformToResult 1
"Remove Small Holes" fire
"Remove Small Holes" setViewerMask 65535
"Remove Small Holes" setPickable 1

set hideNewModules 0
[ {Remove Small Holes} create ImgOut ] setLabel "029_estaillades1_q01_fw085_ss_00001_seg.am"
"029_estaillades1_q01_fw085_ss_00001_seg.am" setIconPosition 406 816
"029_estaillades1_q01_fw085_ss_00001_seg.am" master connect "Remove Small Holes" "ImgOut" 0
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap connect "labels.am"
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap setDefaultAlpha 0.500000
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap activateLocalRange 1
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap setLocalMinMax 1.000000 8.000000
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap enableAlpha 1
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap enableAlphaToggle 1
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap setAutoAdjustRangeMode 1
"029_estaillades1_q01_fw085_ss_00001_seg.am" sharedColormap setColorbarMinMax 1 8
"029_estaillades1_q01_fw085_ss_00001_seg.am" fire
"029_estaillades1_q01_fw085_ss_00001_seg.am" primary setIndex 0 0
"029_estaillades1_q01_fw085_ss_00001_seg.am" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"029_estaillades1_q01_fw085_ss_00001_seg.am" fire
"029_estaillades1_q01_fw085_ss_00001_seg.am" setViewerMask 65535

set name_trim [string trimright $name "00001_0001.rec.16bit.tif"]
set output [append name_trim _seg.tif]
029_estaillades1_q01_fw085_ss_00001_seg.am exportData "3D Tiff" $output
cd ..
remove "temperature.icol" "labels.am" "Result2" "Result2.thresholded" "029_estaillades1_q01_fw085_ss_Resampled.am" "Result2.masked" "Result2.filtered" "029_estaillades1_q01_fw085_ss_00001_seg.am" "Arithmetic" "Interactive Thresholding" "Mask" "Remove Small Spots" "Remove Small Holes"
unset pwd
unset temp
}
