# Avizo Project 950
# Avizo
# Generated by Avizo 9.5.0
remove -all
remove "grayScale.am" "physics.icol" "pore_space_segmented.am" "029_estaillades1_q01_fw085_ss_00088_seg.am" "029_estaillades1_q01_fw085_ss_00088_seg.view" "pore_space_segmented.view" "029_estallaides1_q01_fw085_ss_00088.am" "Extract Subvolume" "Extract Subvolume 2" "Arithmetic"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show


set hideNewModules 0
[ load Y:/live/data_processing/pore_space_segmented.am ] setLabel "pore_space_segmented.am"
"pore_space_segmented.am" setIconPosition 401 42
"pore_space_segmented.am" sharedColormap disconnect
"pore_space_segmented.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"pore_space_segmented.am" sharedColormap setDefaultAlpha 0.500000
"pore_space_segmented.am" sharedColormap activateLocalRange 1
"pore_space_segmented.am" sharedColormap setLocalMinMax 0.000000 1.000000
"pore_space_segmented.am" sharedColormap enableAlpha 1
"pore_space_segmented.am" sharedColormap enableAlphaToggle 1
"pore_space_segmented.am" sharedColormap setAutoAdjustRangeMode 1
"pore_space_segmented.am" sharedColormap setColorbarMinMax 0 1
"pore_space_segmented.am" fire
"pore_space_segmented.am" primary setIndex 0 0
"pore_space_segmented.am" fire
"pore_space_segmented.am" setViewerMask 16383 

set hideNewModules 0
create HxLatticeAccess "Extract Subvolume 2"
"Extract Subvolume 2" setIconPosition 415 89
"Extract Subvolume 2" setVar "CustomHelp" {HxLatticeAccess}
"Extract Subvolume 2" data connect "pore_space_segmented.am"
"Extract Subvolume 2" time setMinMax 0 1
"Extract Subvolume 2" time setSubMinMax 0 1
"Extract Subvolume 2" time setValue 0
"Extract Subvolume 2" time setDiscrete 0
"Extract Subvolume 2" time setIncrement 0.01
"Extract Subvolume 2" time animationMode -once
"Extract Subvolume 2" time setAnimationDelay 10
"Extract Subvolume 2" fire
"Extract Subvolume 2" dataset setIndex 0 0
"Extract Subvolume 2" boxUnits setValue 0
"Extract Subvolume 2" boxMin setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume 2" boxMin setValue 0 650
"Extract Subvolume 2" boxMin setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume 2" boxMin setValue 1 1000
"Extract Subvolume 2" boxMin setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume 2" boxMin setValue 2 1060
"Extract Subvolume 2" boxSize setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume 2" boxSize setValue 0 200
"Extract Subvolume 2" boxSize setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume 2" boxSize setValue 1 200
"Extract Subvolume 2" boxSize setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume 2" boxSize setValue 2 200
"Extract Subvolume 2" options setValue 0 0
"Extract Subvolume 2" options setToggleVisible 0 1
"Extract Subvolume 2" options setValue 1 0
"Extract Subvolume 2" options setToggleVisible 1 1
"Extract Subvolume 2" options setValue 2 1
"Extract Subvolume 2" options setToggleVisible 2 0
"Extract Subvolume 2" subsample setMinMax 0 -16777216 16777216
"Extract Subvolume 2" subsample setValue 0 4
"Extract Subvolume 2" subsample setMinMax 1 -16777216 16777216
"Extract Subvolume 2" subsample setValue 1 4
"Extract Subvolume 2" subsample setMinMax 2 -16777216 16777216
"Extract Subvolume 2" subsample setValue 2 4
"Extract Subvolume 2" timeSlider setMinMax 0 0
"Extract Subvolume 2" timeSlider setButtons 1
"Extract Subvolume 2" timeSlider setEditButton 1
"Extract Subvolume 2" timeSlider setIncrement 1
"Extract Subvolume 2" timeSlider setValue 0
"Extract Subvolume 2" timeSlider setSubMinMax 0 0
"Extract Subvolume 2" applyTransformToResult 1
"Extract Subvolume 2" fire
"Extract Subvolume 2" setViewerMask 16383
"Extract Subvolume 2" setPickable 1

set hideNewModules 0
[ "Extract Subvolume 2" create ] setLabel "pore_space_segmented.view"
"pore_space_segmented.view" setIconPosition 364 124
"pore_space_segmented.view" master connect "Extract Subvolume 2" "result" 0
"pore_space_segmented.view" fire
"pore_space_segmented.view" primary setIndex 0 0
"pore_space_segmented.view" fire
"pore_space_segmented.view" setViewerMask 16383
 
 
#*****************User Input*******************
set Parent_dir Y:/live/029_estaillades1_q01_fw085_ss/
#*****************User Input*******************

cd $Parent_dir
set files [glob -type d *]
set files_sort [lsort $files]

#length of file 
set f [llength $files_sort] 

for {set j 0} {$j<$f} {incr j} {
set Parent_dir Y:/live/029_estaillades1_q01_fw085_ss/
set file_name [lindex $files_sort $j]
set pwd [append Parent_dir $file_name]
set temp [glob -directory $pwd *.tif]
set name [lindex $temp 0]
set n [llength $temp]
cd $file_name
set hideNewModules 1

[ load *seg.am] setLabel "029_estaillades1_q01_fw085_ss_00088_seg.am"
"029_estaillades1_q01_fw085_ss_00088_seg.am" setIconPosition 401 42
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap disconnect
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap setDefaultColor 0.8 0.8 0.8
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap setDefaultAlpha 0.500000
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap activateLocalRange 1
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap setLocalMinMax 0.000000 1.000000
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap enableAlpha 1
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap enableAlphaToggle 1
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap setAutoAdjustRangeMode 1
"029_estaillades1_q01_fw085_ss_00088_seg.am" sharedColormap setColorbarMinMax 0 1
"029_estaillades1_q01_fw085_ss_00088_seg.am" fire
"029_estaillades1_q01_fw085_ss_00088_seg.am" primary setIndex 0 0
"029_estaillades1_q01_fw085_ss_00088_seg.am" fire
"029_estaillades1_q01_fw085_ss_00088_seg.am" setViewerMask 16383


set hideNewModules 0
create HxLatticeAccess "Extract Subvolume"
"Extract Subvolume" setIconPosition 160 82
"Extract Subvolume" setVar "CustomHelp" {HxLatticeAccess}
"Extract Subvolume" data connect "029_estaillades1_q01_fw085_ss_00088_seg.am"
"Extract Subvolume" time setMinMax 0 1
"Extract Subvolume" time setSubMinMax 0 1
"Extract Subvolume" time setValue 0
"Extract Subvolume" time setDiscrete 0
"Extract Subvolume" time setIncrement 0.01
"Extract Subvolume" time animationMode -once
"Extract Subvolume" time setAnimationDelay 10
"Extract Subvolume" fire
"Extract Subvolume" dataset setIndex 0 0
"Extract Subvolume" boxUnits setValue 0
"Extract Subvolume" boxMin setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxMin setValue 0 650
"Extract Subvolume" boxMin setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxMin setValue 1 1000
"Extract Subvolume" boxMin setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxMin setValue 2 1060
"Extract Subvolume" boxSize setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxSize setValue 0 200
"Extract Subvolume" boxSize setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxSize setValue 1 200
"Extract Subvolume" boxSize setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Extract Subvolume" boxSize setValue 2 200
"Extract Subvolume" options setValue 0 0
"Extract Subvolume" options setToggleVisible 0 1
"Extract Subvolume" options setValue 1 0
"Extract Subvolume" options setToggleVisible 1 1
"Extract Subvolume" options setValue 2 1
"Extract Subvolume" options setToggleVisible 2 0
"Extract Subvolume" subsample setMinMax 0 -16777216 16777216
"Extract Subvolume" subsample setValue 0 4
"Extract Subvolume" subsample setMinMax 1 -16777216 16777216
"Extract Subvolume" subsample setValue 1 4
"Extract Subvolume" subsample setMinMax 2 -16777216 16777216
"Extract Subvolume" subsample setValue 2 4
"Extract Subvolume" timeSlider setMinMax 0 0
"Extract Subvolume" timeSlider setButtons 1
"Extract Subvolume" timeSlider setEditButton 1
"Extract Subvolume" timeSlider setIncrement 1
"Extract Subvolume" timeSlider setValue 0
"Extract Subvolume" timeSlider setSubMinMax 0 0
"Extract Subvolume" applyTransformToResult 1
"Extract Subvolume" fire
"Extract Subvolume" setViewerMask 16383
"Extract Subvolume" setPickable 1

set hideNewModules 0
[ "Extract Subvolume" create ] setLabel "029_estaillades1_q01_fw085_ss_00088_seg.view"
"029_estaillades1_q01_fw085_ss_00088_seg.view" setIconPosition 20 118
"029_estaillades1_q01_fw085_ss_00088_seg.view" master connect "Extract Subvolume" "result" 0
"029_estaillades1_q01_fw085_ss_00088_seg.view" fire
"029_estaillades1_q01_fw085_ss_00088_seg.view" primary setIndex 0 0
"029_estaillades1_q01_fw085_ss_00088_seg.view" fire
"029_estaillades1_q01_fw085_ss_00088_seg.view" setViewerMask 16383


set hideNewModules 0
create HxArithmetic "Arithmetic"
"Arithmetic" setIconPosition 306 178
"Arithmetic" setVar "CustomHelp" {HxArithmetic}
"Arithmetic" inputA connect "pore_space_segmented.view"
"Arithmetic" inputB connect "029_estaillades1_q01_fw085_ss_00088_seg.view"
"Arithmetic" fire
"Arithmetic" resultChannels setIndex 0 0
"Arithmetic" nValues setMinMax 0 -16777216 16777216
"Arithmetic" nValues setValue 0 1
"Arithmetic" expr0 setState {a+b}
"Arithmetic" resultType setValue 0
"Arithmetic" resultLocation setValue 0
"Arithmetic" resolution setMinMax 0 1 100000
"Arithmetic" resolution setValue 0 64
"Arithmetic" resolution setMinMax 1 1 100000
"Arithmetic" resolution setValue 1 64
"Arithmetic" resolution setMinMax 2 1 100000
"Arithmetic" resolution setValue 2 64
"Arithmetic" minBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 0 -1
"Arithmetic" minBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 1 -1
"Arithmetic" minBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" minBox setValue 2 -1
"Arithmetic" maxBox setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 0 1
"Arithmetic" maxBox setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 1 1
"Arithmetic" maxBox setMinMax 2 -3.40282346638529e+038 3.40282346638529e+038
"Arithmetic" maxBox setValue 2 1
"Arithmetic" options setValue 0 0
"Arithmetic" options setToggleVisible 0 1
"Arithmetic" applyTransformToResult 1
"Arithmetic" fire
"Arithmetic" setViewerMask 16383
"Arithmetic" setPickable 1


set hideNewModules 0
[ "Arithmetic" create ] setLabel "result.view"
"result.view" setIconPosition 364 124
"result.view" master connect "Extract Subvolume 2" "result" 0
"result.view" fire
"result.view" primary setIndex 0 0
"result.view" fire
"result.view" setViewerMask 16383

cd ..
cd time_series_subvolume
set output [append file_name _N2subvolume.am]
"029_estaillades1_q01_fw085_ss_00088_seg.view" save "AmiraMesh" $output
remove "result.view" "Arithmetic" "029_estaillades1_q01_fw085_ss_00088_seg.view" "029_estaillades1_q01_fw085_ss_00088_seg.am" "Extract Subvolume"
cd .. 
}

